// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe_46zagU-mL98aZoih-jZjcsxgDDP6Bg',
    appId: '1:94063122501:web:7a26207b867300fdb0ab2c',
    messagingSenderId: '94063122501',
    projectId: 'venue-6fc62',
    authDomain: 'venue-6fc62.firebaseapp.com',
    storageBucket: 'venue-6fc62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQYPwIV4dIPukmLkEWJRK4wQYDB4sKyNc',
    appId: '1:94063122501:android:ab16ef7f2107d90eb0ab2c',
    messagingSenderId: '94063122501',
    projectId: 'venue-6fc62',
    storageBucket: 'venue-6fc62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDBPs-BO1LbrEPfboOZTnebRrIhLTuyjM',
    appId: '1:94063122501:ios:cee696b1f2053dc7b0ab2c',
    messagingSenderId: '94063122501',
    projectId: 'venue-6fc62',
    storageBucket: 'venue-6fc62.appspot.com',
    iosBundleId: 'com.example.venue',
  );
}
